vich_uploader:
    db_driver: orm
    mappings:
        produits_image:
            uri_prefix: /images/produit
            upload_destination: '%kernel.project_dir%/public/images/produit'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
